name: Acceptance

on:
  push:
    branches-ignore:
      - main

jobs:
  pre-commit-check:
    name: Pre-commit check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Code Autoformat
        id: format
        run: uv run pre-commit run --all-files

  check-tests:
    name: Tests and coverage check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run coverage run -m pytest && uv run coverage report -i --fail-under=80

  check-version-support:
    name: Validate Python version support
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Run tests
        run: uv run --python ${{ matrix.python-version }} pytest
